### ISSUE TITLE
Why, in your code, the calculation of idl_out and blurred_out in BSPM_TORCH does not require ODE solver?

### ISSUE THREAD

**Issue by coderaBruce** [jeongwhanchoi/BSPM#1]

**Comment by jeongwhanchoi** [comment]
In the BSPM model, the blurring process uses the Euler method, and the blurring time is 1. 
So, in the setting where the Euler method is used and the blurring time is 1, the results of `idl_out` and `blurred_out` are the same without using the ode function as expressed by the Euler method. 

To reduce the code complexity, we omit the calculation of the ODE solver in `BSPM_TORCH`.

I hope this answer is helpful to you.
