### ISSUE TITLE
Failure to train normally on a new dataset

### ISSUE THREAD

**Issue by BlueGhostYi** [jeongwhanchoi/BSPM#2]
Hi, Author. Thanks a lot for publicizing such an excellent new work. I tried to run BSPM on my new dataset (the dataset format is the same as in the BSPM source code) but got very low test results:
```
training time for BSPM 1.1621246337890625
{'precision': array([0.00047602]), 'recall': array([0.00014337]), 'ndcg': array([0.00048853])}
```

The final performance of the output is the same (recall@20=0.00014337) regardless of any hyper-parameters (e.g., T_b, T_s, factor_dim, idl_beta) I set. I don't know how to modify it to get the correct result?

Thanks again and I look forward to your reply.

**Comment by jeongwhanchoi** [comment]
Hello @BlueGhostYi ,

Thank you for your interest in our work 😄 .

Can you tell me how to use the adjacency matrix and how sparse the number of interactions in the dataset you used is?
If you prefer to discuss details by email, please send an email to jeongwhan.choi@yonsei.ac.kr. I hope I can help as much as possible.

Best,
Jeongwhan
